name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build with Gradle
      env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          GROUP_ID: ${{ secrets.GROUP_ID }}
          BDUSS: ${{ secrets.BDUSS }}
          FILE_DIR: twrp下载和说明
          FILE_NAME: twrp机型下载地址汇总-wzsx150_2020.03.17.xls
      run: |
          chmod 777 ./app/post.sh
          ./app/post.sh
