name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build with Gradle
      env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          GROUP_ID: ${{ secrets.GROUP_ID }}
          BDUSS: ${{ secrets.BDUSS }}
          FILE_DIR: 刷機/V20/F800 8.0 ROM
          FILE_NAME: F800自用8.0.zip
      run: |
          chmod 777 ./app/post.sh
          ./app/post.sh
